# Generated by Django 6.0.6 on 2026-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('province', models.CharField(choices=[('ALA', 'Alajuela'), ('CAR', 'Cartago'), ('GUA', 'Guanacaste'), ('HER', 'Heredia'), ('LIM', 'Limón'), ('SAN', 'San José')], default='ALA', max_length=3)),
                ('reward_for_information', models.BooleanField(default=False)),
                ('last_time_been_seen_at', models.DateTimeField(verbose_name='Last time been seen')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
